import { createContext, useContext, useState } from "react";

export const LANGUAGES = [
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "zh", label: "中文", flag: "🇹🇼" },
  { code: "ms", label: "Bahasa", flag: "🇲🇾" },
];

export const T = {
  en: {
    // App
    appName: "Wandersplit",
    appSubtitle: "Travel expenses, beautifully tracked",
    // Auth
    email: "Email",
    username: "Username",
    usernameOrEmail: "Username or Email",
    password: "Password",
    signIn: "Sign In",
    signUp: "Sign Up",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    continueWithGoogle: "Continue with Google",
    pleaseWait: "Please wait…",
    or: "or",
    // Nav
    trips: "Trips",
    receipts: "Receipts",
    gallery: "Gallery",
    people: "People",
    summary: "Summary",
    settings: "Settings",
    // Trips
    myTrips: "My Trips",
    selectOrCreate: "Select or create a trip to get started",
    newTrip: "New Trip",
    noTripsYet: "No trips yet",
    createFirstTrip: "Create your first trip to start tracking expenses together.",
    createYourFirstTrip: "Create Your First Trip",
    editTrip: "Edit Trip",
    tripName: "Trip Name",
    startDate: "Start Date",
    endDate: "End Date",
    baseCurrency: "Base Currency",
    driveFolderID: "Google Drive Folder ID",
    driveFolderHint: "Photos and receipts will be uploaded to this Drive folder.",
    currencyHint: "All amounts in this trip will use this currency.",
    active: "Active",
    icon: "Icon",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    tripUpdated: "Trip updated ✓",
    tripCreated: "Trip created ✓",
    confirmDeleteTrip: "Delete \"%s\"? This cannot be undone.",
    tripDeleted: "Trip deleted",
    // People
    peopleTitle: "People",
    participants: "%d participant",
    participantsPlural: "%d participants",
    addPerson: "Add Person",
    editPerson: "Edit Person",
    noPersonYet: "No people yet",
    addParticipants: "Add trip participants to start splitting expenses.",
    addFirstPerson: "Add First Person",
    personUpdated: "Person updated ✓",
    personAdded: "Person added ✓",
    personRemoved: "Person removed",
    confirmRemove: "Remove %s?",
    name: "Name",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other / Prefer not to say",
    generate: "🎲 Generate",
    upload: "📷 Upload",
    seed: "Seed (name or phrase)",
    seedPlaceholder: "Enter any text to generate avatar",
    style: "Style",
    uploadImage: "Upload Image",
    // Receipts
    receiptsTitle: "Receipts",
    receiptsSubtitle: "%d receipt · %s total",
    receiptsSubtitlePlural: "%d receipts · %s total",
    addReceipt: "Add Receipt",
    noReceiptsYet: "No receipts yet",
    addFirstExpense: "Add your first expense or upload a receipt photo.",
    addFirstReceipt: "Add First Receipt",
    editReceipt: "Edit Receipt",
    uploadReceiptPhoto: "Upload receipt photo",
    autoFillOCR: "Auto-fill with OCR analysis",
    uploadBtn: "Upload",
    analyzing: "Analyzing…",
    analyzingText: "Analyzing receipt with Vision API…",
    receiptAnalyzed: "Receipt analyzed! Please review.",
    ocrFailed: "OCR failed — please fill in manually",
    restaurantPlace: "Restaurant / Place *",
    date: "Date",
    total: "Total (%s) *",
    whoPaid: "Who Paid?",
    items: "Items",
    addItem: "Add Item",
    noItemsNote: "No items — total will be split among participants",
    itemsTotal: "Items total",
    splitAmong: "Split Among",
    all: "All",
    location: "Location (optional)",
    googleMapsLink: "Google Maps link",
    latitude: "Latitude",
    longitude: "Longitude",
    saving: "Saving…",
    saveReceipt: "Save Receipt",
    receiptUpdated: "Receipt updated ✓",
    receiptSaved: "Receipt saved ✓",
    receiptDeleted: "Receipt deleted",
    confirmDeleteReceipt: "Delete this receipt?",
    whoAte: "Who ate \"%s\"?",
    selectAll: "Select All",
    clear: "Clear",
    selected: "%d selected",
    confirm: "Confirm (%d person)",
    confirmPlural: "Confirm (%d people)",
    viewOnMap: "📍 View on map",
    moreItems: "+%d more items",
    // Summary
    summaryTitle: "Summary",
    totalTripSpend: "Total Trip Spend",
    receiptsCount: "%d receipts · %d people",
    individualBalances: "Individual Balances",
    paid: "Paid",
    owes: "Owes",
    whoOwesWhom: "Who Owes Whom",
    allSettled: "All settled!",
    noOutstanding: "No outstanding debts.",
    everythingSettled: "Everything settled!",
    record: "Record",
    settled: "Settled ✓",
    cleared: "Cleared",
    // Gallery
    galleryTitle: "Gallery",
    photosCount: "%d photo",
    photosCountPlural: "%d photos",
    uploadPhoto: "+ Upload",
    noPhotosYet: "No photos yet",
    preserveMemories: "Upload photos from your trip to preserve memories.",
    uploadFirstPhoto: "Upload First Photo",
    uploadPhotoTitle: "Upload Photo",
    note: "Note (optional)",
    notePlaceholder: "Add a caption...",
    mapsLink: "Google Maps Link (optional)",
    uploadToDrive: "Upload to Drive",
    savePhoto: "Save Photo",
    noDriveFolderWarning: "⚠ No Drive folder set. Photo will be saved as data URL only.",
    photoUploaded: "Photo uploaded ✓",
    photoDeleted: "Photo deleted",
    confirmDeletePhoto: "Delete this photo?",
    uploadFailed: "Upload failed: %s",
    // Settings
    settingsTitle: "Settings",
    account: "Account",
    signOut: "Sign Out",
    currentTrip: "Current Trip",
    currency: "Currency",
    driveFolder: "Drive Folder",
    notSet: "Not set",
    about: "About",
    aboutText: "Wandersplit — Travel Expense Tracker\nBuilt with React + Firebase + Google Drive API",
    language: "Language",
    // No trip
    noTripSelected: "No trip selected",
    selectTripFirst: "Please select or create a trip first.",
    // Errors
    fillRequired: "Please fill in required fields",
  },

  zh: {
    appName: "Wandersplit",
    appSubtitle: "旅行账单，轻松记录",
    email: "电子邮件",
    username: "用户名",
    usernameOrEmail: "用户名或电子邮件",
    password: "密码",
    signIn: "登录",
    signUp: "注册",
    createAccount: "创建账户",
    alreadyHaveAccount: "已有账户？",
    dontHaveAccount: "还没有账户？",
    continueWithGoogle: "使用 Google 登录",
    pleaseWait: "请稍候…",
    or: "或",
    trips: "行程",
    receipts: "账单",
    gallery: "相册",
    people: "成员",
    summary: "结算",
    settings: "设置",
    myTrips: "我的行程",
    selectOrCreate: "选择或创建一个行程",
    newTrip: "新行程",
    noTripsYet: "还没有行程",
    createFirstTrip: "创建第一个行程来记录共同花费。",
    createYourFirstTrip: "创建第一个行程",
    editTrip: "编辑行程",
    tripName: "行程名称",
    startDate: "开始日期",
    endDate: "结束日期",
    baseCurrency: "基准货币",
    driveFolderID: "Google Drive 文件夹 ID",
    driveFolderHint: "照片和收据将上传至此文件夹。",
    currencyHint: "此行程所有金额均使用该货币。",
    active: "当前",
    icon: "图标",
    saveChanges: "保存更改",
    cancel: "取消",
    tripUpdated: "行程已更新 ✓",
    tripCreated: "行程已创建 ✓",
    confirmDeleteTrip: "删除「%s」？此操作不可撤销。",
    tripDeleted: "行程已删除",
    peopleTitle: "成员",
    participants: "%d 位成员",
    participantsPlural: "%d 位成员",
    addPerson: "添加成员",
    editPerson: "编辑成员",
    noPersonYet: "还没有成员",
    addParticipants: "添加行程成员来开始分账。",
    addFirstPerson: "添加第一位成员",
    personUpdated: "成员已更新 ✓",
    personAdded: "成员已添加 ✓",
    personRemoved: "成员已删除",
    confirmRemove: "删除 %s？",
    name: "姓名",
    gender: "性别",
    male: "男",
    female: "女",
    other: "其他 / 不愿透露",
    generate: "🎲 生成头像",
    upload: "📷 上传",
    seed: "种子（名字或短语）",
    seedPlaceholder: "输入任意文字生成头像",
    style: "风格",
    uploadImage: "上传图片",
    receiptsTitle: "账单",
    receiptsSubtitle: "%d 条账单 · 合计 %s",
    receiptsSubtitlePlural: "%d 条账单 · 合计 %s",
    addReceipt: "添加账单",
    noReceiptsYet: "还没有账单",
    addFirstExpense: "添加第一笔消费或上传收据照片。",
    addFirstReceipt: "添加第一条账单",
    editReceipt: "编辑账单",
    uploadReceiptPhoto: "上传收据照片",
    autoFillOCR: "OCR 自动识别填写",
    uploadBtn: "上传",
    analyzing: "识别中…",
    analyzingText: "正在使用 Vision API 识别收据…",
    receiptAnalyzed: "收据识别完成！请确认内容。",
    ocrFailed: "OCR 识别失败，请手动填写",
    restaurantPlace: "餐厅 / 地点 *",
    date: "日期",
    total: "金额（%s）*",
    whoPaid: "谁付款？",
    items: "明细",
    addItem: "添加明细",
    noItemsNote: "无明细 — 将平均分摊给参与者",
    itemsTotal: "明细合计",
    splitAmong: "分摊给",
    all: "全选",
    location: "位置（可选）",
    googleMapsLink: "Google 地图链接",
    latitude: "纬度",
    longitude: "经度",
    saving: "保存中…",
    saveReceipt: "保存账单",
    receiptUpdated: "账单已更新 ✓",
    receiptSaved: "账单已保存 ✓",
    receiptDeleted: "账单已删除",
    confirmDeleteReceipt: "删除此账单？",
    whoAte: "谁吃了「%s」？",
    selectAll: "全选",
    clear: "清除",
    selected: "已选 %d 人",
    confirm: "确认（%d 人）",
    confirmPlural: "确认（%d 人）",
    viewOnMap: "📍 查看地图",
    moreItems: "还有 %d 项",
    summaryTitle: "结算",
    totalTripSpend: "行程总消费",
    receiptsCount: "%d 条账单 · %d 位成员",
    individualBalances: "个人余额",
    paid: "已付",
    owes: "应付",
    whoOwesWhom: "债务关系",
    allSettled: "全部结清！",
    noOutstanding: "没有未结清债务。",
    everythingSettled: "全部结清！",
    record: "记录",
    settled: "已结清 ✓",
    cleared: "已清算",
    galleryTitle: "相册",
    photosCount: "%d 张照片",
    photosCountPlural: "%d 张照片",
    uploadPhoto: "+ 上传",
    noPhotosYet: "还没有照片",
    preserveMemories: "上传旅行照片，留住美好回忆。",
    uploadFirstPhoto: "上传第一张照片",
    uploadPhotoTitle: "上传照片",
    note: "备注（可选）",
    notePlaceholder: "添加说明…",
    mapsLink: "Google 地图链接（可选）",
    uploadToDrive: "上传到 Drive",
    savePhoto: "保存照片",
    noDriveFolderWarning: "⚠ 未设置 Drive 文件夹，照片将以 data URL 保存。",
    photoUploaded: "照片已上传 ✓",
    photoDeleted: "照片已删除",
    confirmDeletePhoto: "删除此照片？",
    uploadFailed: "上传失败：%s",
    settingsTitle: "设置",
    account: "账户",
    signOut: "退出登录",
    currentTrip: "当前行程",
    currency: "货币",
    driveFolder: "Drive 文件夹",
    notSet: "未设置",
    about: "关于",
    aboutText: "Wandersplit — 旅行分账记录\n基于 React + Firebase + Google Drive API",
    language: "语言",
    noTripSelected: "未选择行程",
    selectTripFirst: "请先选择或创建一个行程。",
    fillRequired: "请填写必填项",
  },

  ms: {
    appName: "Wandersplit",
    appSubtitle: "Perbelanjaan perjalanan, dicatat dengan indah",
    email: "E-mel",
    username: "Nama Pengguna",
    usernameOrEmail: "Nama Pengguna atau E-mel",
    password: "Kata Laluan",
    signIn: "Log Masuk",
    signUp: "Daftar",
    createAccount: "Buat Akaun",
    alreadyHaveAccount: "Sudah ada akaun?",
    dontHaveAccount: "Belum ada akaun?",
    continueWithGoogle: "Teruskan dengan Google",
    pleaseWait: "Sila tunggu…",
    or: "atau",
    trips: "Perjalanan",
    receipts: "Resit",
    gallery: "Galeri",
    people: "Ahli",
    summary: "Ringkasan",
    settings: "Tetapan",
    myTrips: "Perjalanan Saya",
    selectOrCreate: "Pilih atau buat perjalanan baru",
    newTrip: "Perjalanan Baru",
    noTripsYet: "Tiada perjalanan lagi",
    createFirstTrip: "Buat perjalanan pertama untuk mula mencatat perbelanjaan.",
    createYourFirstTrip: "Buat Perjalanan Pertama",
    editTrip: "Edit Perjalanan",
    tripName: "Nama Perjalanan",
    startDate: "Tarikh Mula",
    endDate: "Tarikh Tamat",
    baseCurrency: "Mata Wang Asas",
    driveFolderID: "ID Folder Google Drive",
    driveFolderHint: "Foto dan resit akan dimuat naik ke folder ini.",
    currencyHint: "Semua amaun dalam perjalanan ini menggunakan mata wang ini.",
    active: "Aktif",
    icon: "Ikon",
    saveChanges: "Simpan Perubahan",
    cancel: "Batal",
    tripUpdated: "Perjalanan dikemas kini ✓",
    tripCreated: "Perjalanan dicipta ✓",
    confirmDeleteTrip: "Padam \"%s\"? Ini tidak boleh dibuat asal.",
    tripDeleted: "Perjalanan dipadam",
    peopleTitle: "Ahli",
    participants: "%d peserta",
    participantsPlural: "%d peserta",
    addPerson: "Tambah Ahli",
    editPerson: "Edit Ahli",
    noPersonYet: "Tiada ahli lagi",
    addParticipants: "Tambah peserta untuk mula membahagi perbelanjaan.",
    addFirstPerson: "Tambah Ahli Pertama",
    personUpdated: "Ahli dikemas kini ✓",
    personAdded: "Ahli ditambah ✓",
    personRemoved: "Ahli dikeluarkan",
    confirmRemove: "Keluarkan %s?",
    name: "Nama",
    gender: "Jantina",
    male: "Lelaki",
    female: "Perempuan",
    other: "Lain-lain",
    generate: "🎲 Jana",
    upload: "📷 Muat Naik",
    seed: "Benih (nama atau frasa)",
    seedPlaceholder: "Masukkan teks untuk jana avatar",
    style: "Gaya",
    uploadImage: "Muat Naik Gambar",
    receiptsTitle: "Resit",
    receiptsSubtitle: "%d resit · Jumlah %s",
    receiptsSubtitlePlural: "%d resit · Jumlah %s",
    addReceipt: "Tambah Resit",
    noReceiptsYet: "Tiada resit lagi",
    addFirstExpense: "Tambah perbelanjaan pertama atau muat naik foto resit.",
    addFirstReceipt: "Tambah Resit Pertama",
    editReceipt: "Edit Resit",
    uploadReceiptPhoto: "Muat naik foto resit",
    autoFillOCR: "Isi automatik dengan OCR",
    uploadBtn: "Muat Naik",
    analyzing: "Menganalisis…",
    analyzingText: "Menganalisis resit dengan Vision API…",
    receiptAnalyzed: "Resit dianalisis! Sila semak.",
    ocrFailed: "OCR gagal — sila isi secara manual",
    restaurantPlace: "Restoran / Tempat *",
    date: "Tarikh",
    total: "Jumlah (%s) *",
    whoPaid: "Siapa yang Bayar?",
    items: "Item",
    addItem: "Tambah Item",
    noItemsNote: "Tiada item — jumlah akan dibahagi sama rata",
    itemsTotal: "Jumlah item",
    splitAmong: "Bahagi Kepada",
    all: "Semua",
    location: "Lokasi (pilihan)",
    googleMapsLink: "Pautan Google Maps",
    latitude: "Latitud",
    longitude: "Longitud",
    saving: "Menyimpan…",
    saveReceipt: "Simpan Resit",
    receiptUpdated: "Resit dikemas kini ✓",
    receiptSaved: "Resit disimpan ✓",
    receiptDeleted: "Resit dipadam",
    confirmDeleteReceipt: "Padam resit ini?",
    whoAte: "Siapa makan \"%s\"?",
    selectAll: "Pilih Semua",
    clear: "Kosongkan",
    selected: "%d dipilih",
    confirm: "Sahkan (%d orang)",
    confirmPlural: "Sahkan (%d orang)",
    viewOnMap: "📍 Lihat di peta",
    moreItems: "+%d item lagi",
    summaryTitle: "Ringkasan",
    totalTripSpend: "Jumlah Perbelanjaan",
    receiptsCount: "%d resit · %d orang",
    individualBalances: "Baki Individu",
    paid: "Dibayar",
    owes: "Berhutang",
    whoOwesWhom: "Siapa Berhutang Siapa",
    allSettled: "Semua selesai!",
    noOutstanding: "Tiada hutang tertunggak.",
    everythingSettled: "Semua telah diselesaikan!",
    record: "Rekod",
    settled: "Selesai ✓",
    cleared: "Diselesaikan",
    galleryTitle: "Galeri",
    photosCount: "%d foto",
    photosCountPlural: "%d foto",
    uploadPhoto: "+ Muat Naik",
    noPhotosYet: "Tiada foto lagi",
    preserveMemories: "Muat naik foto perjalanan untuk kenangan indah.",
    uploadFirstPhoto: "Muat Naik Foto Pertama",
    uploadPhotoTitle: "Muat Naik Foto",
    note: "Nota (pilihan)",
    notePlaceholder: "Tambah kapsyen...",
    mapsLink: "Pautan Google Maps (pilihan)",
    uploadToDrive: "Muat Naik ke Drive",
    savePhoto: "Simpan Foto",
    noDriveFolderWarning: "⚠ Tiada folder Drive. Foto akan disimpan sebagai data URL.",
    photoUploaded: "Foto dimuat naik ✓",
    photoDeleted: "Foto dipadam",
    confirmDeletePhoto: "Padam foto ini?",
    uploadFailed: "Muat naik gagal: %s",
    settingsTitle: "Tetapan",
    account: "Akaun",
    signOut: "Log Keluar",
    currentTrip: "Perjalanan Semasa",
    currency: "Mata Wang",
    driveFolder: "Folder Drive",
    notSet: "Tidak ditetapkan",
    about: "Tentang",
    aboutText: "Wandersplit — Penjejak Perbelanjaan Perjalanan\nDibina dengan React + Firebase + Google Drive API",
    language: "Bahasa",
    noTripSelected: "Tiada perjalanan dipilih",
    selectTripFirst: "Sila pilih atau buat perjalanan dahulu.",
    fillRequired: "Sila isi medan yang diperlukan",
  },
};

// Helper: replace %s or %d in translation string
export function t(str, ...args) {
  if (!str) return "";
  let i = 0;
  return str.replace(/%[sd]/g, () => args[i++] ?? "");
}

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const stored = typeof localStorage !== "undefined" ? localStorage.getItem("lang") : null;
  const [lang, setLang] = useState(stored || "en");

  const changeLang = (code) => {
    setLang(code);
    localStorage.setItem("lang", code);
  };

  const tr = T[lang] || T.en;

  return (
    <LangContext.Provider value={{ lang, changeLang, tr, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
